# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

human_equilibrium_fast <- function(EIR, ft, p, age0, ghnodes, ghweights) {
    .Call('malariaModelFit_human_equilibrium_fast', PACKAGE = 'malariaModelFit', EIR, ft, p, age0, ghnodes, ghweights)
}

