# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

human_equilibrium_cpp <- function(EIR, ft, p, age0, ghnodes, ghweights) {
    .Call('_malariaModelFit_human_equilibrium_cpp', PACKAGE = 'malariaModelFit', EIR, ft, p, age0, ghnodes, ghweights)
}

runMCMC <- function(nrep, data_key, datasets, age0, ghnodes0, ghweights0, ghnodes1, ghweights1, update_blocks) {
    .Call('_malariaModelFit_runMCMC', PACKAGE = 'malariaModelFit', nrep, data_key, datasets, age0, ghnodes0, ghweights0, ghnodes1, ghweights1, update_blocks)
}

dummy1_cpp <- function() {
    invisible(.Call('_malariaModelFit_dummy1_cpp', PACKAGE = 'malariaModelFit'))
}

