# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

human_equilibrium_cpp <- function(EIR, ft, p, age_, h) {
    .Call(`_malariaModelFit_human_equilibrium_cpp`, EIR, ft, p, age_, h)
}

